# Generated by Django 4.2.2 on 2023-06-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='steps',
            field=models.JSONField(null=True),
        ),
    ]
