# Generated by Django 4.2.2 on 2023-07-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(default='tranier', on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
