# Generated by Django 4.2.2 on 2023-07-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0017_alter_user_email'),
        ('members', '0003_remove_member_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(default='Trainee', on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
