# Generated by Django 4.2.2 on 2023-07-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0017_alter_user_email'),
        ('members', '0004_member_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
