# Generated by Django 4.2.2 on 2023-07-08 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0006_remove_member_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Trainee', to=settings.AUTH_USER_MODEL),
        ),
    ]
