# Generated by Django 4.2.2 on 2023-07-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_group',
        ),
    ]
